import './globals.scss'
import { AppContextProvider } from '../config/Store';
import Nav from '../components/Nav';
import Footer from '../components/Footer';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <AppContextProvider>
          <Nav />
          {children}
          <Footer />
        </AppContextProvider>
      </body>
    </html>
  )
}
